// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: agent.proto

package agentpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Agent_Ping_FullMethodName           = "/voidgridbackup.agent.v1.Agent/Ping"
	Agent_InitRepository_FullMethodName = "/voidgridbackup.agent.v1.Agent/InitRepository"
	Agent_Backup_FullMethodName         = "/voidgridbackup.agent.v1.Agent/Backup"
	Agent_ListSnapshots_FullMethodName  = "/voidgridbackup.agent.v1.Agent/ListSnapshots"
	Agent_ListDirectory_FullMethodName  = "/voidgridbackup.agent.v1.Agent/ListDirectory"
	Agent_Restore_FullMethodName        = "/voidgridbackup.agent.v1.Agent/Restore"
	Agent_ListStacks_FullMethodName     = "/voidgridbackup.agent.v1.Agent/ListStacks"
	Agent_RestoreStack_FullMethodName   = "/voidgridbackup.agent.v1.Agent/RestoreStack"
	Agent_ImportDump_FullMethodName     = "/voidgridbackup.agent.v1.Agent/ImportDump"
	Agent_ListVMs_FullMethodName        = "/voidgridbackup.agent.v1.Agent/ListVMs"
	Agent_RestoreVM_FullMethodName      = "/voidgridbackup.agent.v1.Agent/RestoreVM"
	Agent_Check_FullMethodName          = "/voidgridbackup.agent.v1.Agent/Check"
	Agent_DeleteSnapshot_FullMethodName = "/voidgridbackup.agent.v1.Agent/DeleteSnapshot"
	Agent_WipeRepository_FullMethodName = "/voidgridbackup.agent.v1.Agent/WipeRepository"
	Agent_Maintain_FullMethodName       = "/voidgridbackup.agent.v1.Agent/Maintain"
	Agent_TestRepository_FullMethodName = "/voidgridbackup.agent.v1.Agent/TestRepository"
	Agent_MoveRepository_FullMethodName = "/voidgridbackup.agent.v1.Agent/MoveRepository"
	Agent_PathUsage_FullMethodName      = "/voidgridbackup.agent.v1.Agent/PathUsage"
	Agent_RepoStats_FullMethodName      = "/voidgridbackup.agent.v1.Agent/RepoStats"
	Agent_Logs_FullMethodName           = "/voidgridbackup.agent.v1.Agent/Logs"
)

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Agent is served by every voidgrid-backup-agent. The server dials agents.
//
// An agent gets its certificate by registering with the server (see
// registry.proto); until an operator approves it, it refuses every RPC. After
// that it requires a client cert signed by the server's CA.
type AgentClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// Backup repository operations. The server sends the repository config and
	// password with every call; the agent keeps only a local Kopia cache.
	InitRepository(ctx context.Context, in *InitRepositoryRequest, opts ...grpc.CallOption) (*InitRepositoryResponse, error)
	Backup(ctx context.Context, in *BackupRequest, opts ...grpc.CallOption) (*BackupResponse, error)
	ListSnapshots(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (*ListSnapshotsResponse, error)
	ListDirectory(ctx context.Context, in *ListDirectoryRequest, opts ...grpc.CallOption) (*ListDirectoryResponse, error)
	Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*RestoreResponse, error)
	// Docker compose stacks.
	ListStacks(ctx context.Context, in *ListStacksRequest, opts ...grpc.CallOption) (*ListStacksResponse, error)
	RestoreStack(ctx context.Context, in *RestoreStackRequest, opts ...grpc.CallOption) (*RestoreResponse, error)
	ImportDump(ctx context.Context, in *ImportDumpRequest, opts ...grpc.CallOption) (*ImportDumpResponse, error)
	// libvirt virtual machines.
	ListVMs(ctx context.Context, in *ListVMsRequest, opts ...grpc.CallOption) (*ListVMsResponse, error)
	RestoreVM(ctx context.Context, in *RestoreVMRequest, opts ...grpc.CallOption) (*RestoreResponse, error)
	// Repository check: verifies snapshot metadata, that every content blob
	// exists, and (with ECC on) repairs bitrot found along the way.
	Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error)
	// Removing backups. DeleteSnapshot forgets one snapshot (space comes back
	// only after later maintenance). WipeRepository deletes every blob in the
	// repository's storage, no repository password needed. Maintain runs a full
	// maintenance cycle if this agent is the repository's maintenance owner.
	DeleteSnapshot(ctx context.Context, in *DeleteSnapshotRequest, opts ...grpc.CallOption) (*DeleteSnapshotResponse, error)
	WipeRepository(ctx context.Context, in *WipeRepositoryRequest, opts ...grpc.CallOption) (*WipeRepositoryResponse, error)
	Maintain(ctx context.Context, in *MaintainRequest, opts ...grpc.CallOption) (*MaintainResponse, error)
	// Editing a repository's location. TestRepository connects to the storage
	// in the request and opens the repository there (it never creates one);
	// warnings are non-fatal findings, e.g. a filesystem path that is not a
	// network mount. MoveRepository renames the repository's directory from the
	// location in `repository` to the one in new_config_json (SFTP and
	// filesystem only) and refuses if the destination exists.
	TestRepository(ctx context.Context, in *TestRepositoryRequest, opts ...grpc.CallOption) (*TestRepositoryResponse, error)
	MoveRepository(ctx context.Context, in *MoveRepositoryRequest, opts ...grpc.CallOption) (*MoveRepositoryResponse, error)
	// Host filesystem sizes, for choosing what to back up.
	PathUsage(ctx context.Context, in *PathUsageRequest, opts ...grpc.CallOption) (*PathUsageResponse, error)
	// Space a repository takes in its storage (all Kopia blobs). Lists every
	// blob, so it is O(blob count): meant to be run on demand and cached.
	RepoStats(ctx context.Context, in *RepoStatsRequest, opts ...grpc.CallOption) (*RepoStatsResponse, error)
	// The agent's recent log lines, kept in memory (lost when it restarts).
	Logs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (*LogsResponse, error)
}

type agentClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentClient(cc grpc.ClientConnInterface) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, Agent_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) InitRepository(ctx context.Context, in *InitRepositoryRequest, opts ...grpc.CallOption) (*InitRepositoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitRepositoryResponse)
	err := c.cc.Invoke(ctx, Agent_InitRepository_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Backup(ctx context.Context, in *BackupRequest, opts ...grpc.CallOption) (*BackupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BackupResponse)
	err := c.cc.Invoke(ctx, Agent_Backup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ListSnapshots(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (*ListSnapshotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSnapshotsResponse)
	err := c.cc.Invoke(ctx, Agent_ListSnapshots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ListDirectory(ctx context.Context, in *ListDirectoryRequest, opts ...grpc.CallOption) (*ListDirectoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDirectoryResponse)
	err := c.cc.Invoke(ctx, Agent_ListDirectory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*RestoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreResponse)
	err := c.cc.Invoke(ctx, Agent_Restore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ListStacks(ctx context.Context, in *ListStacksRequest, opts ...grpc.CallOption) (*ListStacksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStacksResponse)
	err := c.cc.Invoke(ctx, Agent_ListStacks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) RestoreStack(ctx context.Context, in *RestoreStackRequest, opts ...grpc.CallOption) (*RestoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreResponse)
	err := c.cc.Invoke(ctx, Agent_RestoreStack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ImportDump(ctx context.Context, in *ImportDumpRequest, opts ...grpc.CallOption) (*ImportDumpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportDumpResponse)
	err := c.cc.Invoke(ctx, Agent_ImportDump_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ListVMs(ctx context.Context, in *ListVMsRequest, opts ...grpc.CallOption) (*ListVMsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVMsResponse)
	err := c.cc.Invoke(ctx, Agent_ListVMs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) RestoreVM(ctx context.Context, in *RestoreVMRequest, opts ...grpc.CallOption) (*RestoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreResponse)
	err := c.cc.Invoke(ctx, Agent_RestoreVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckResponse)
	err := c.cc.Invoke(ctx, Agent_Check_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) DeleteSnapshot(ctx context.Context, in *DeleteSnapshotRequest, opts ...grpc.CallOption) (*DeleteSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSnapshotResponse)
	err := c.cc.Invoke(ctx, Agent_DeleteSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) WipeRepository(ctx context.Context, in *WipeRepositoryRequest, opts ...grpc.CallOption) (*WipeRepositoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WipeRepositoryResponse)
	err := c.cc.Invoke(ctx, Agent_WipeRepository_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Maintain(ctx context.Context, in *MaintainRequest, opts ...grpc.CallOption) (*MaintainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MaintainResponse)
	err := c.cc.Invoke(ctx, Agent_Maintain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) TestRepository(ctx context.Context, in *TestRepositoryRequest, opts ...grpc.CallOption) (*TestRepositoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestRepositoryResponse)
	err := c.cc.Invoke(ctx, Agent_TestRepository_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) MoveRepository(ctx context.Context, in *MoveRepositoryRequest, opts ...grpc.CallOption) (*MoveRepositoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MoveRepositoryResponse)
	err := c.cc.Invoke(ctx, Agent_MoveRepository_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) PathUsage(ctx context.Context, in *PathUsageRequest, opts ...grpc.CallOption) (*PathUsageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PathUsageResponse)
	err := c.cc.Invoke(ctx, Agent_PathUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) RepoStats(ctx context.Context, in *RepoStatsRequest, opts ...grpc.CallOption) (*RepoStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoStatsResponse)
	err := c.cc.Invoke(ctx, Agent_RepoStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) Logs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (*LogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogsResponse)
	err := c.cc.Invoke(ctx, Agent_Logs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServer is the server API for Agent service.
// All implementations must embed UnimplementedAgentServer
// for forward compatibility.
//
// Agent is served by every voidgrid-backup-agent. The server dials agents.
//
// An agent gets its certificate by registering with the server (see
// registry.proto); until an operator approves it, it refuses every RPC. After
// that it requires a client cert signed by the server's CA.
type AgentServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// Backup repository operations. The server sends the repository config and
	// password with every call; the agent keeps only a local Kopia cache.
	InitRepository(context.Context, *InitRepositoryRequest) (*InitRepositoryResponse, error)
	Backup(context.Context, *BackupRequest) (*BackupResponse, error)
	ListSnapshots(context.Context, *ListSnapshotsRequest) (*ListSnapshotsResponse, error)
	ListDirectory(context.Context, *ListDirectoryRequest) (*ListDirectoryResponse, error)
	Restore(context.Context, *RestoreRequest) (*RestoreResponse, error)
	// Docker compose stacks.
	ListStacks(context.Context, *ListStacksRequest) (*ListStacksResponse, error)
	RestoreStack(context.Context, *RestoreStackRequest) (*RestoreResponse, error)
	ImportDump(context.Context, *ImportDumpRequest) (*ImportDumpResponse, error)
	// libvirt virtual machines.
	ListVMs(context.Context, *ListVMsRequest) (*ListVMsResponse, error)
	RestoreVM(context.Context, *RestoreVMRequest) (*RestoreResponse, error)
	// Repository check: verifies snapshot metadata, that every content blob
	// exists, and (with ECC on) repairs bitrot found along the way.
	Check(context.Context, *CheckRequest) (*CheckResponse, error)
	// Removing backups. DeleteSnapshot forgets one snapshot (space comes back
	// only after later maintenance). WipeRepository deletes every blob in the
	// repository's storage, no repository password needed. Maintain runs a full
	// maintenance cycle if this agent is the repository's maintenance owner.
	DeleteSnapshot(context.Context, *DeleteSnapshotRequest) (*DeleteSnapshotResponse, error)
	WipeRepository(context.Context, *WipeRepositoryRequest) (*WipeRepositoryResponse, error)
	Maintain(context.Context, *MaintainRequest) (*MaintainResponse, error)
	// Editing a repository's location. TestRepository connects to the storage
	// in the request and opens the repository there (it never creates one);
	// warnings are non-fatal findings, e.g. a filesystem path that is not a
	// network mount. MoveRepository renames the repository's directory from the
	// location in `repository` to the one in new_config_json (SFTP and
	// filesystem only) and refuses if the destination exists.
	TestRepository(context.Context, *TestRepositoryRequest) (*TestRepositoryResponse, error)
	MoveRepository(context.Context, *MoveRepositoryRequest) (*MoveRepositoryResponse, error)
	// Host filesystem sizes, for choosing what to back up.
	PathUsage(context.Context, *PathUsageRequest) (*PathUsageResponse, error)
	// Space a repository takes in its storage (all Kopia blobs). Lists every
	// blob, so it is O(blob count): meant to be run on demand and cached.
	RepoStats(context.Context, *RepoStatsRequest) (*RepoStatsResponse, error)
	// The agent's recent log lines, kept in memory (lost when it restarts).
	Logs(context.Context, *LogsRequest) (*LogsResponse, error)
	mustEmbedUnimplementedAgentServer()
}

// UnimplementedAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServer struct{}

func (UnimplementedAgentServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedAgentServer) InitRepository(context.Context, *InitRepositoryRequest) (*InitRepositoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitRepository not implemented")
}
func (UnimplementedAgentServer) Backup(context.Context, *BackupRequest) (*BackupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Backup not implemented")
}
func (UnimplementedAgentServer) ListSnapshots(context.Context, *ListSnapshotsRequest) (*ListSnapshotsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSnapshots not implemented")
}
func (UnimplementedAgentServer) ListDirectory(context.Context, *ListDirectoryRequest) (*ListDirectoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDirectory not implemented")
}
func (UnimplementedAgentServer) Restore(context.Context, *RestoreRequest) (*RestoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Restore not implemented")
}
func (UnimplementedAgentServer) ListStacks(context.Context, *ListStacksRequest) (*ListStacksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListStacks not implemented")
}
func (UnimplementedAgentServer) RestoreStack(context.Context, *RestoreStackRequest) (*RestoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestoreStack not implemented")
}
func (UnimplementedAgentServer) ImportDump(context.Context, *ImportDumpRequest) (*ImportDumpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportDump not implemented")
}
func (UnimplementedAgentServer) ListVMs(context.Context, *ListVMsRequest) (*ListVMsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVMs not implemented")
}
func (UnimplementedAgentServer) RestoreVM(context.Context, *RestoreVMRequest) (*RestoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestoreVM not implemented")
}
func (UnimplementedAgentServer) Check(context.Context, *CheckRequest) (*CheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedAgentServer) DeleteSnapshot(context.Context, *DeleteSnapshotRequest) (*DeleteSnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSnapshot not implemented")
}
func (UnimplementedAgentServer) WipeRepository(context.Context, *WipeRepositoryRequest) (*WipeRepositoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WipeRepository not implemented")
}
func (UnimplementedAgentServer) Maintain(context.Context, *MaintainRequest) (*MaintainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Maintain not implemented")
}
func (UnimplementedAgentServer) TestRepository(context.Context, *TestRepositoryRequest) (*TestRepositoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestRepository not implemented")
}
func (UnimplementedAgentServer) MoveRepository(context.Context, *MoveRepositoryRequest) (*MoveRepositoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MoveRepository not implemented")
}
func (UnimplementedAgentServer) PathUsage(context.Context, *PathUsageRequest) (*PathUsageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PathUsage not implemented")
}
func (UnimplementedAgentServer) RepoStats(context.Context, *RepoStatsRequest) (*RepoStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RepoStats not implemented")
}
func (UnimplementedAgentServer) Logs(context.Context, *LogsRequest) (*LogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logs not implemented")
}
func (UnimplementedAgentServer) mustEmbedUnimplementedAgentServer() {}
func (UnimplementedAgentServer) testEmbeddedByValue()               {}

// UnsafeAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServer will
// result in compilation errors.
type UnsafeAgentServer interface {
	mustEmbedUnimplementedAgentServer()
}

func RegisterAgentServer(s grpc.ServiceRegistrar, srv AgentServer) {
	// If the following call pancis, it indicates UnimplementedAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Agent_ServiceDesc, srv)
}

func _Agent_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_InitRepository_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRepositoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).InitRepository(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_InitRepository_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).InitRepository(ctx, req.(*InitRepositoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Backup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Backup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_Backup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Backup(ctx, req.(*BackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ListSnapshots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSnapshotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ListSnapshots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ListSnapshots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ListSnapshots(ctx, req.(*ListSnapshotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ListDirectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDirectoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ListDirectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ListDirectory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ListDirectory(ctx, req.(*ListDirectoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Restore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Restore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_Restore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Restore(ctx, req.(*RestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ListStacks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStacksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ListStacks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ListStacks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ListStacks(ctx, req.(*ListStacksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_RestoreStack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreStackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).RestoreStack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_RestoreStack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).RestoreStack(ctx, req.(*RestoreStackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ImportDump_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportDumpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ImportDump(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ImportDump_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ImportDump(ctx, req.(*ImportDumpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ListVMs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVMsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ListVMs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ListVMs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ListVMs(ctx, req.(*ListVMsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_RestoreVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).RestoreVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_RestoreVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).RestoreVM(ctx, req.(*RestoreVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_Check_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Check(ctx, req.(*CheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_DeleteSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).DeleteSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_DeleteSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).DeleteSnapshot(ctx, req.(*DeleteSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_WipeRepository_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WipeRepositoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).WipeRepository(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_WipeRepository_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).WipeRepository(ctx, req.(*WipeRepositoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Maintain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MaintainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Maintain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_Maintain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Maintain(ctx, req.(*MaintainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_TestRepository_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestRepositoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).TestRepository(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_TestRepository_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).TestRepository(ctx, req.(*TestRepositoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_MoveRepository_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveRepositoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).MoveRepository(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_MoveRepository_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).MoveRepository(ctx, req.(*MoveRepositoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_PathUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PathUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).PathUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_PathUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).PathUsage(ctx, req.(*PathUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_RepoStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepoStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).RepoStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_RepoStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).RepoStats(ctx, req.(*RepoStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_Logs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Logs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_Logs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Logs(ctx, req.(*LogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Agent_ServiceDesc is the grpc.ServiceDesc for Agent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Agent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "voidgridbackup.agent.v1.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Agent_Ping_Handler,
		},
		{
			MethodName: "InitRepository",
			Handler:    _Agent_InitRepository_Handler,
		},
		{
			MethodName: "Backup",
			Handler:    _Agent_Backup_Handler,
		},
		{
			MethodName: "ListSnapshots",
			Handler:    _Agent_ListSnapshots_Handler,
		},
		{
			MethodName: "ListDirectory",
			Handler:    _Agent_ListDirectory_Handler,
		},
		{
			MethodName: "Restore",
			Handler:    _Agent_Restore_Handler,
		},
		{
			MethodName: "ListStacks",
			Handler:    _Agent_ListStacks_Handler,
		},
		{
			MethodName: "RestoreStack",
			Handler:    _Agent_RestoreStack_Handler,
		},
		{
			MethodName: "ImportDump",
			Handler:    _Agent_ImportDump_Handler,
		},
		{
			MethodName: "ListVMs",
			Handler:    _Agent_ListVMs_Handler,
		},
		{
			MethodName: "RestoreVM",
			Handler:    _Agent_RestoreVM_Handler,
		},
		{
			MethodName: "Check",
			Handler:    _Agent_Check_Handler,
		},
		{
			MethodName: "DeleteSnapshot",
			Handler:    _Agent_DeleteSnapshot_Handler,
		},
		{
			MethodName: "WipeRepository",
			Handler:    _Agent_WipeRepository_Handler,
		},
		{
			MethodName: "Maintain",
			Handler:    _Agent_Maintain_Handler,
		},
		{
			MethodName: "TestRepository",
			Handler:    _Agent_TestRepository_Handler,
		},
		{
			MethodName: "MoveRepository",
			Handler:    _Agent_MoveRepository_Handler,
		},
		{
			MethodName: "PathUsage",
			Handler:    _Agent_PathUsage_Handler,
		},
		{
			MethodName: "RepoStats",
			Handler:    _Agent_RepoStats_Handler,
		},
		{
			MethodName: "Logs",
			Handler:    _Agent_Logs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent.proto",
}
